
# Aux links for the upper right navigation
aux_links:
  "About":
    - "https://github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

remote_theme: just-the-docs/just-the-docs
