title: MSU Denver - ESIIL Stars Project 2023
description: Water Quantity, Quality, and Accessibility 
on the Diné (Navajo) Reservation
remote_theme: just-the-docs/just-the-docs


# Aux links for the upper right navigation
aux_links:
  "About":
    - "https://cu-esiil-edu.github.io/MSUDenver-DineWaterQuality2023/About"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Set a path/url to a logo that will be displayed instead of the title
#logo: "https://github.com/cu-esiil-edu/MSUDenver-DineWaterQuality2023/blob/main/AnimasPolluted.jpg"


