
layout: default
title: Dine Water Quality
nav_order: 8
remote_theme: just-the-docs/just-the-docs

 navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Background
      url: 


# Aux links for the upper right navigation
aux_links:
  "About":
    - "https://cu-esiil-edu.github.io/MSUDenver-DineWaterQuality2023/About"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Set a path/url to a logo that will be displayed instead of the title
#logo: "https://github.com/cu-esiil-edu/MSUDenver-DineWaterQuality2023/blob/main/AnimasPolluted.jpg"


